### ISSUE TITLE
Module build failed: TypeError

### ISSUE THREAD

**Issue by albatrosary** [KadoTomohiro/angular2-minimum#1]
`npm start`実行後にTypeErrorになります。同様に `npm run start:ngc`でも同じエラーになります。

```
$ npm start

> angular2-minimum@1.0.0 start /Users/albatrosary/Sandbox/angular2-minimum
> npm run webpack && npm run lite


> angular2-minimum@1.0.0 webpack /Users/albatrosary/Sandbox/angular2-minimum
> webpack --config webpack.config.js

Hash: 944640c3b2fef0789509
Version: webpack 2.1.0-beta.22
Time: 401ms
                      Asset     Size  Chunks             Chunk Names
        bootstrap.bundle.js  2.82 kB       0  [emitted]  bootstrap
    bootstrap.aot.bundle.js  2.82 kB       1  [emitted]  bootstrap.aot
    bootstrap.bundle.js.map  2.54 kB       0  [emitted]  bootstrap
bootstrap.aot.bundle.js.map  2.55 kB       1  [emitted]  bootstrap.aot
    + 2 hidden modules

ERROR in ./src/main.ts
Module build failed: TypeError: Can't add property fileName, object is not extensible
    at Object.Linter (/Users/albatrosary/Sandbox/angular2-minimum/node_modules/tslint/lib/tslint.js:12:23)

ERROR in ./src/main.aot.ts
Module build failed: TypeError: Can't add property fileName, object is not extensible
    at Object.Linter (/Users/albatrosary/Sandbox/angular2-minimum/node_modules/tslint/lib/tslint.js:12:23)
```

**Comment by KadoTomohiro** [comment]
tslint-loaderがpackage.jsonに登録されていなかったため、登録しました。また、`npm run start:ngc`を`npm run start:aot`に修正しました。

**Comment by NoWHereRepo** [comment]
Could you please translate to english? I have the same error
Thanks :)

**Comment by pdelanauze** [comment]
@NoWHereRepo For me I was just missing the tslint-loader , so `npm install tslint-loader --save-dev` fixed it
